# fly.toml app configuration file generated for pgtest-whatever-inc on 2025-11-19T19:08:46-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'webclient-whatever-inc'
primary_region = 'iad'

[build]
dockerfile = "Dockerfile-web"

[env]
  SERVER_URL = "https://flytest-server-whatever-inc.fly.dev"
  SOME_OTHER_CONFIG = "value"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
