# fly.toml app configuration file for seng401-project-zopac server
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'seng401-project-zopac'
primary_region = 'iad'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '3000'
  HOSTNAME = '0.0.0.0'
  POSTGRES_HOST = 'seng401-project-zopac-postgres.internal'
  POSTGRES_PORT = '5432'
  POSTGRES_DATABASE = 'appdb'
  POSTGRES_USER = 'appuser'
  CLIENT_URL = 'https://seng401-project-zopac-client.fly.dev'
  AUTH_URL = 'https://seng401-project-zopac.fly.dev/api/auth'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/api/hello"
    protocol = "http"
    tls_skip_verify = false

    [http_service.checks.headers]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
